spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: kfylsi13
#    url: ${DB_URL:''}
#    username: ${USER_NAME:''}
#    password: ${PASSWORD:''}
    driverClassName: org.postgresql.Driver
server:
  port: 5000

app:
  version: 1.0.0

